### ISSUE TITLE
Momentum buffers still created and computed even if beta1 is 0

### ISSUE THREAD

**Issue by evanatyourservice** [google-deepmind/optax#1010]
With methods like schedule-free gaining popularity, should someone go through all the transforms and only create and use momentum if beta1>0? Could save a lot of memory. I would be willing to take the time if it seems beneficial

**Comment by fabianp** [comment]
huh. This sounds interesting!. I think we just have to make sure this would be compatible with things like inject_hyperparams (https://optax.readthedocs.io/en/latest/api/optimizer_schedules.html#optax.inject_hyperparams) that allows to change hyperparameters on the fly. 

What do you thnk @vroulet ?

**Comment by evanatyourservice** [comment]
@fabianp Oh yeah good point, it might be hard with inject hp, for example this is my version of adam with optional mu:

```
    def init_fn(params):
        if b1 > 0:
            mu = otu.tree_zeros_like(params, dtype=mu_dtype)
        else:
            mu = None
        nu = otu.tree_zeros_like(params)
        return transform.ScaleByAdamState(count=jnp.zeros([], jnp.int32), mu=mu, nu=nu)

    def update_fn(updates, state, params=None):
        del params
        count_inc = numerics.safe_int32_increment(state.count)
        if b1 > 0:
            mu = otu.tree_update_moment(updates, state.mu, b1, 1)
            if nesterov:
                mu_hat = jax.tree.map(
                    lambda m, g: b1 * m + (1 - b1) * g,
                    otu.tree_bias_correction(
                        mu, b1, numerics.safe_int32_increment(count_inc)
                    ),
                    otu.tree_bias_correction(updates, b1, count_inc),
                )
            else:
                mu_hat = otu.tree_bias_correction(mu, b1, count_inc)
            mu = otu.tree_cast(mu, mu_dtype)
        else:
            mu = None
            mu_hat = updates
        nu = otu.tree_update_moment_per_elem_norm(updates, state.nu, b2, 2)
        nu_hat = otu.tree_bias_correction(nu, b2, count_inc)
        updates = jax.tree.map(
            lambda m, v: m / (jnp.sqrt(v + eps_root) + eps), mu_hat, nu_hat
        )
        return updates, transform.ScaleByAdamState(count=count_inc, mu=mu, nu=nu)
```

but not having momentum buffers from init and those if then statements wouldn't be inject hp friendly. Also, here instead of momentum I use just the grads for numerator, but there may be cases that aren't so straightforward on what to replace momentum with.

**Comment by vroulet** [comment]
Yes, that's exactly what I was thinking about in #1006 (just for rmsprop) but not in such general way (just to make the current schedulefree_adamw more memory friendly)

**Comment by evanatyourservice** [comment]
@vroulet that sounds like a good compromise so folks can at least skip momentum by using schedule free adam from the contrib... changing all the optimizers in optax might be too much crazy work lol
