### ISSUE TITLE
Wrong formula for `softmax_cross_entropy` in online doc

### ISSUE THREAD

**Issue by ziyuanzhao2000** [google-deepmind/optax#1040]
On the latest version of this [page](https://optax.readthedocs.io/en/latest/api/losses.html#optax.losses.softmax_cross_entropy) it says each element of the output vector from the `softmax_cross_entropy` should be 

$$
\sigma_i = \log \left(\frac{\sum_j  y_{ij} \exp(x_{ij}) }{\sum_j \exp(x_{ij})} \right)
$$

But clearly, based on the [source code](https://github.com/google-deepmind/optax/blob/main/optax/losses/_classification.py#L209#L274) it's a typo and should be the following instead:

$$
\sigma_i = -\sum_j  y_{ij} \log \left(\frac{ \exp(x_{ij}) }{\sum_j \exp(x_{ij})} \right)
$$

Please fix this so as not to confuse other users; thank you!

**Comment by fabianp** [comment]
good catch @ziyuanzhao2000 . I proposed a fix here: https://github.com/google-deepmind/optax/pull/1041
