### ISSUE TITLE
Python 3.8 Compatibility Errors

### ISSUE THREAD

**Issue by jcraisbeck** [google-deepmind/optax#1075]
Hello,

Sorry if this is poorly formatted, I don't often submit issues like this.

There are three files in contrib that aren't fully compatible with Python 3.8 because of issues with typing, because objects that should be initialized as a Tuple are initialized as tuples, and in once case because Tuple isn't in the initial import from typing. Could this be fixed in the following files?

dadapt_adamw.py,
combine.py,
prodigy.py.

**Comment by vroulet** [comment]
Hello @jcraisbeck 
No worries, issues are welcome.
Indeed optax only supports python>=3.9 and indeed the only unsupported items should be the typings (I believe such issue may appear in many files).
We prefer to align with most recent practices in python and for this reason we removed support for python 3.8.
Could you explain why can't you use python>=3.9?
Thanks !
