### ISSUE TITLE
Adopt US spelling for the documentation

### ISSUE THREAD

**Issue by fabianp** [google-deepmind/optax#1084]
Make sure the documentation is consistently using US spelling. Currently it's a mixed bag, for example:
![image](https://github.com/user-attachments/assets/e37e4cc5-0c04-45f1-8c08-33c2b9231de6)

**Comment by miguelcsx** [comment]
Hi @fabianp  I'm working on this issue, I'd appreciate it if you could assign it to me. :+1:
