### ISSUE TITLE
Jax 0.4.34 raises an error for None as tree-prefix

### ISSUE THREAD

**Issue by a1302z** [google-deepmind/optax#1093]
Hello:)

[The most recent release of jax 0.4.34](https://github.com/jax-ml/jax/releases/tag/jax-v0.4.34) does no longer support anything of the kind `jax.tree.map(f, None, non-None)`. 

This also affects optax, for example, in [add_decayed_weights](https://github.com/google-deepmind/optax/blob/main/optax/transforms/_adding.py#L50). 

The error can be simply prevented by changing the line to 

```
    updates = jtu.tree_map(
        lambda g, p: None if g is None else g + weight_decay * p, updates, params, is_leaf=lambda x: x is None)
```

I'm happy to take a look and see if there are any other parts affected and provide a pull request if desired. 

Best, 
Alex

**Comment by vroulet** [comment]
Hello @a1302z,
Thank you very much for pointing this.
We used an automatic tool to catch this error and make a pass on our codebase to fix this (see e.g. [here](https://github.com/google-deepmind/optax/blob/789212c920ac559b13dfe09a19a5efd7bd678d56/optax/tree_utils/_tree_math.py#L315)) but it seems that it did not catch all occurrences. If you are willing to do a PR for that, that would be great! And if not, I'd be curious to know how you flagged them.
