### ISSUE TITLE
Add a projection onto L1 unit ball

### ISSUE THREAD

**Issue by jialinyi94** [google-deepmind/optax#1100]
Projection onto L1 unit ball is extremly useful for sparse solution. Quite surprising that is is not included in: [optax/projections/_projections.py](https://github.com/google-deepmind/optax/blob/main/optax/projections/_projections.py).

I would love to contribute it.

**Comment by mblondel** [comment]
I actually need it for my work too and have implemented it in JAXopt so I will add it.

**Comment by mblondel** [comment]
Fixed by 85378ad4ce1c19dfd218c65873f8941776c3eaca.
