### ISSUE TITLE
Move examples from Readme into docs.

### ISSUE THREAD

**Issue by rosshemsley** [google-deepmind/optax#229]
We have a number of examples in the Readme, but we should move them to ReadTheDocs.

**Comment by Carlosbogo** [comment]
Hi, I would like to work on this. Is there anyone doing it already?

**Comment by mkunesch** [comment]
Hi! That would be great - thanks a lot!

@rosshemsley recently added a similar example to ReadTheDocs in PR #231 so it might help to look at that PR (to roughly match the style and see where the files should go).

Thanks a lot again and let us know if you have any questions!

**Comment by Carlosbogo** [comment]
Sorry for the delay, I couldn't find time to work on this until now.

It's my first time working on this repository so I'm not sure what exactly should I do: 
Should I remove the examples from the Readme after moving them into docs or should I keep them there?
Should I move them into the [docs](https://github.com/deepmind/optax/tree/master/docs) file or to the [examples](https://github.com/deepmind/optax/tree/master/examples) file, or maybe somewhere else?

**Comment by rosshemsley** [comment]
Hey @Carlosbogo, no worries about delay - we are happy to have contributors :)

Perhaps we could leave the examples in the readme for now, and start by moving things into the docs?

One thing that could be nice is to extend the Quickstart section to include some of the examples from the docs.

This could be done, e.g. by adding another notebook with the examples in the same style as https://github.com/deepmind/optax/blob/master/docs/optax-101.ipynb

A nice property about colabs is that they are run when the documentation is built, which ensures they do not break (and also, we can make it possible for users to run them themselves).

We are quite open to ideas on how to present the examples! Maybe one tip would be try to make a small change first (e.g. moving one example from the readme into a colab), that way we can quickly provide help and feedback.

**Comment by Warlord-K** [comment]
Hi @rosshemsley , Please Review my PR since this is my first contribution it needs to be reviewed by a maintainer. Please Let me know if any modifications are needed.
