### ISSUE TITLE
What's the difference between `add_decayed_weights` and `additive_weight_decay`?

### ISSUE THREAD

**Issue by samuela** [google-deepmind/optax#307]
There does not seem to be any discussion in the documentation? What's the difference between these two? What's the kosher way to implement weight decay?

**Comment by samuela** [comment]
And based on https://github.com/deepmind/optax/blob/7c76078015469ad00805063cfd772c1564f37640/optax/_src/transform.py#L915 it looks as though they're identical. But there's no deprecation warning or anything...

**Comment by mkunesch** [comment]
Good point! There is a comment there that they are legacy aliases but currently no deprecation warning. We could either write a quick deprecation wrapper ourselves or use a deprecation library (e.g. perhaps https://github.com/briancurtin/deprecation)?

We could wrap the legacy alias in both `transform.py` and `utils.py` with the current version as "deprecated_in" and 1.0.0 for "removed_in"? I think it makes sense to keep them around with a warning while we are still in the 0. versions.

Would you like to file a PR for this? (No worries if not - just making sure we don't duplicate work)

Thanks a lot!

**Comment by samuela** [comment]
> Would you like to file a PR for this? (No worries if not - just making sure we don't duplicate work)

I don't currently have the bandwidth to submit a PR for this unfortunately. Admittedly I'm a bit hesitant since there doesn't seem to be an established precedent for how to deprecate things --- an inherent catch-22!

**Comment by chandrima91** [comment]
I'd like to work on this please. What kind of functionality would you like in making the deprecation wrapper?

**Comment by mkunesch** [comment]
Hey! Great, thanks a lot!

I think at this point it would be nice if the wrapper/decorator could:

- warn with a DeprecationWarning (with a message saying that this function/alias might be removed in a future version).
- add a line saying that the function/alias is deprecated to the function docstring.
- accept an optional version string specifying when the deprecation started and add it to the messages above.
- accept an optional string specifying what to use instead and add it to the messages above.

I don't think we need functionality for automatic removal yet - we are keeping the aliases around for checkpoint compatibility and so I don't think we should tie this to a specific version at this point.

Thanks a lot again and let me know if you have any questions!

**Comment by vroulet** [comment]
The aliases have been removed.
