### ISSUE TITLE
BFGS / Quasi-Newton optimizers

### ISSUE THREAD

**Issue by nasyxx** [google-deepmind/optax#446]
Hi, will optax consider implementing BFGS/Quasi-Newton optimizers?

Not sure if there is something similar already.

**Comment by adam-hartshorne** [comment]
Is available here,

https://github.com/google/jaxopt

**Comment by nasyxx** [comment]
> Is available in this accompanying library,
> 
> [google/jaxopt](https://github.com/google/jaxopt)

Thanks!  I completely ignored jaxopt as a part of the JAX ecosystem.

**Comment by alonfnt** [comment]
> We keep optax focused on stochastic optimisation and deep learning workloads, you can find a number of additional optimisation methods in jaxopt

Now that jaxopt is in maintenance mode and says it will be merge to optax, how true is that statement? Is optax going to include non-stochastic optimizers? And if so, should this issue be reopened?
