### ISSUE TITLE
Adding Contrastive loss functions?

### ISSUE THREAD

**Issue by mahdiabdollahpour** [google-deepmind/optax#452]
Hi
What do you think about adding loss functions in contrastive learning such as N-pair loss (https://papers.nips.cc/paper/2016/hash/6b180037abbebea991d8b1232f8a8ca9-Abstract.html, https://lilianweng.github.io/posts/2021-05-31-contrastive/#n-pair-loss)
Both with In-Batch Negative which is much more efficient and also the classical version.

**Comment by mtthss** [comment]
Closing since we do not have bandwith internally and there were no takers externally
if however @mahdiabdollahpour you want to try putting together a PR I am happy to review

**Comment by mahdiabdollahpour** [comment]
> Closing since we do not have bandwith internally and there were no takers externally if however @mahdiabdollahpour you want to try putting together a PR I am happy to review

I'll work on it and let you know.
