### ISSUE TITLE
How to use ema with pmap?

### ISSUE THREAD

**Issue by vighneshbirodkar** [google-deepmind/optax#474]
Hi

I have a pmapped training pipeline (with multiple hosts) with which I want to use ema for the network parameters. How do I go about doing this? Is there some example of pseudo-code that I can follow?

I am mainly confused about which of the devices has to do an ema or if it has to be done on one of the hosts outside of pmap.

Best
Vighnesh

**Comment by mtthss** [comment]
Apologies for the lack of response on this question.
Generally speaking I would use pmean to average the updates before applying them to the online parameters.
Then since the parameters will stay the same throughout training you can just track the ema on each host and they will stay consistent

**Comment by youurayy** [comment]
What about opt_state -- if it's not distributed/synced and each node maintains its own opt_state, do we then save/restore multiple opt_states?  I think that's the case but would like it confirmed.
