### ISSUE TITLE
Add missing optimizers

### ISSUE THREAD

**Issue by carlosgmartin** [google-deepmind/optax#507]
Add the following optimizers:
- [x] Nadam: [keras](https://keras.io/api/optimizers/Nadam/), [torch](https://pytorch.org/docs/stable/generated/torch.optim.NAdam.html). Pull request: https://github.com/google-deepmind/optax/pull/529
- [x] Adadelta: [keras](https://keras.io/api/optimizers/adadelta/), [torch](https://pytorch.org/docs/stable/generated/torch.optim.Adadelta.html)
- [x] Rprop: [torch](https://pytorch.org/docs/stable/generated/torch.optim.Rprop.html): Pull request: https://github.com/google-deepmind/optax/pull/695
- [x] Ftrl: [keras](https://keras.io/api/optimizers/ftrl/) : #738

**Comment by SauravMaheshkar** [comment]
I'd like to work on the Adadelta implementation.

**Comment by fabianp** [comment]
@SauravMaheshkar : that would be most welcome if you're still interested! Please open a new issue to keep track of that :-)
