### ISSUE TITLE
jax.interpreters.xla.DeviceArray deprecated in jax 0.4.11

### ISSUE THREAD

**Issue by tisabe** [google-deepmind/optax#533]
Hi all, 
I noticed after updating jax to the newest version (0.4.11) I get an error during import of optax:

`AttributeError: module 'jax.interpreters.xla' has no attribute 'DeviceArray'`

After looking into the changelog of jax, it seems `jax.interpreters.xla.DeviceArray` is now deprecated and `jax.Array` should be used.

Edit: Seems hard to reproduce, I installed optax in a new virtual environment where it works fine. Still not working in the old venv.

**Comment by tisabe** [comment]
Update: Seems hard to reproduce, I installed optax in a new virtual environment where it works fine. Still not working in the old venv.

**Comment by hbq1** [comment]
Hi @tisabe, it must have been resolved in the latest versions of the optax's dependencies. 
Let me close this issue for now, but feel free to re-open if you encounter this error again.

**Comment by davzuliani** [comment]
Hi,
I'm sorry for reopening this issue, but I just encountered it.
What is the solution? 

Thanks!

**Comment by tisabe** [comment]
Hi @davzuliani 
For me creating a fresh venv and installing the newest versions of jax and optax worked.

**Comment by tisabe** [comment]
Okay, I tracked down where the issue actually came from. Looks like the `chex` requirement should be updated to `>=v0.1.6` or `>=v0.1.7`. After updating `chex`, this error should be fixed. @hbq1 should this be opened in a new issue?

**Comment by bainro** [comment]
pip install chex==0.1.7 --force-reinstall worked for me!
