### ISSUE TITLE
initialize sharderd optimizer state

### ISSUE THREAD

**Issue by gianlucadetommaso** [google-deepmind/optax#548]
Hi,
assuming that `optimizer` is an Optax optimizer and `params` is a tree of parameters, `optimizer.init(params)` materializes all parameters on a single GPU device, if GPU is available. Two questions:

- is it possible to initialize the parameters on CPU instead, even if GPU is available?

- is it possible to shard the initialization over multiple devices?

Thanks!

**Comment by maxidl** [comment]
The optimizer state will follow the sharding of the params pytree. So if params is sharded across GPU or TPU devices, the optimizer state will usually also be sharded in the same way. However, if params are on CPU, then it seems the optimizer state is still created on GPU/TPU device 0 (the default device in jax), which might result in OOM. You can wrap your code inside `with jax.default_device(jax.devices('cpu')[0]):` which should result in the optimizer state being created on CPU. Afterwards you can shard them as you like.

**Comment by gianlucadetommaso** [comment]
Thanks! I'll try this.

**Comment by fabianp** [comment]
Closing the issue as it seems to me the question has been answered. Please reopen if that's not the case
