### ISSUE TITLE
kl_divergence_with_log_targets is not imported in __init__.py

### ISSUE THREAD

**Issue by h-terao** [google-deepmind/optax#556]
Hi.

kl_divergence_with_log_targets is implemented in optax/_src/loss.py, and is tested in optax/_src/loss_test.py.
However, optax/__init__.py does not import the function so it is not available from optax. I think this is a bug.

**Comment by mtthss** [comment]
This is correct. Do you want to send a PR?

**Comment by h-terao** [comment]
Sorry for the late reply. Yes, I'd like to send a PR.

**Comment by h-terao** [comment]
I sent PR #576

**Comment by amosyou** [comment]
looks like we can close this issue
