### ISSUE TITLE
The corresponding versions between optax and JAX

### ISSUE THREAD

**Issue by TInaWangxue** [google-deepmind/optax#562]
I use jax0.4.1, optax0.0.9.
The error output:
`File "/mnt/data/miniconda/envs/energy_transformer_117/lib/python3.11/site-packages/optax/_src/transform.py", line 80, in _update_moment
    return jax.tree_multimap(
AttributeError: module 'jax' has no attribute 'tree_multimap'`

I search the [https://github.com/google/jax/blob/main/CHANGELOG.md](https://github.com/google/jax/blob/main/CHANGELOG.md), found that 
{func}`jax.tree_util.tree_multimap` has been removed. It has been deprecated since
    JAX release 0.3.5, and {func}`jax.tree_util.tree_map` is a direct replacement.

Besides, I can't use jax0.4.14(the latest version)

I want to  the corresponding versions between optax and JAX, if I use JAX0.4.1,which version of OPTAX I should use?

**Comment by Cynthyi** [comment]
Have you found the solution? I've had the same problem.

**Comment by fabianp** [comment]
It seems to me that the optax version is too low (0.0.9 is from July 2021 while jax 0.4 is from July 2023)

updating optax should solve the issue. In particular, optax >= 0.1.7 should be fine.

**Comment by Alessandro-Castelli** [comment]
Is there official documentation available? I have jax 0.4.23, which version of optax should I use?

**Comment by vroulet** [comment]
Hello @Alessandro-Castelli,
Can't you use the latest one? If not, could you provide an error log?
Documenting correspondences between jax and optax versions may be doable but we would need strong arguments to pursue such endeavor.
And a simple way to check for that would be to look at the date when the jax 0.4.23 was released, see [here](https://github.com/jax-ml/jax/tags), and see the corresponding optax version at that date, see [here](https://github.com/google-deepmind/optax/tags).
