### ISSUE TITLE
For testing, `flax==0.5.3` is incompatible with `jax==0.4.14`

### ISSUE THREAD

**Issue by Rupt** [google-deepmind/optax#568]
Recent tests [fail](https://github.com/deepmind/optax/actions/runs/5845001186/job/15848671933) with:

```shell
__________________ ERROR collecting _src/equivalence_test.py ___________________
ImportError while importing test module '/tmp/optax-env/lib/python3.11/site-packages/optax/_src/equivalence_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
/tmp/optax-env/lib/python3.11/site-packages/optax/_src/equivalence_test.py:21: in <module>
    from flax import optim
/tmp/optax-env/lib/python3.11/site-packages/flax/__init__.py:19: in <module>
    from . import linen as linen
/tmp/optax-env/lib/python3.11/site-packages/flax/linen/__init__.py:47: in <module>
    from .attention import (
/tmp/optax-env/lib/python3.11/site-packages/flax/linen/attention.py:22: in <module>
    from flax.linen.linear import default_kernel_init
/tmp/optax-env/lib/python3.11/site-packages/flax/linen/linear.py:30: in <module>
    from jax import ShapedArray
E   ImportError: cannot import name 'ShapedArray' from 'jax' (/tmp/optax-env/lib/python3.11/site-packages/jax/__init__.py)
```

[JAX 0.4.14 (July 27, 2023)](https://github.com/google/jax/blob/main/CHANGELOG.md#jax-0414-july-27-2023) deletes `jax.ShapedArray`.

>    * `jax.ShapedArray`: use {class}`jax.core.ShapedArray`.

Optax's test suite uses `flax==0.5.3`, because it `equivalence_test.py` uses `flax.optim`, and `flax.optim` [is deleted in the next release](https://github.com/google/flax/compare/v0.5.3...v0.6.0).

Unfortunately, Flax 0.5.3 uses the deleted `jax.ShapedArray`.

A short-term fix is to require `jax<0.4.14` in test environments. In future, the `flax.optim` reference implementations should come from another source.

**Comment by mtthss** [comment]
This should now be fixed
