### ISSUE TITLE
application of hessian operator in second_order

### ISSUE THREAD

**Issue by linjing-lab** [google-deepmind/optax#601]
I just released optimtool to upgrade *hybird* algorithms integrated with proximity operators mainly arange from L1, L2 method, and found the latest research didn't prove second_order method can be applied on the above operations coming from proximity approximation.

The implementation of second_order in optax is [hessian_diag](https://github.com/google-deepmind/optax/blob/9f2f5caeca3030accf608cce934182798b5da7c6/optax/second_order/hessian.py#L60), and [hessian_test](https://github.com/google-deepmind/optax/blob/9f2f5caeca3030accf608cce934182798b5da7c6/optax/second_order/hessian_test.py#L82) execute and verify the exactness of hessian_diag design. For a more compatible use, I didn't find any particular examples correlated to hessian_diag and its efficiency described in [examples](https://github.com/google-deepmind/optax/tree/master/examples), only acknowledge the simple net_fn used in testing the equivalence between [jax_hessian_diag](https://github.com/google-deepmind/optax/blob/9f2f5caeca3030accf608cce934182798b5da7c6/optax/second_order/hessian_test.py#L74) and hessian_diag.

In my insight, I implement newton_variant method mainly for reseaching a complicated function, like the underlying example:
```python
import optimtool.unconstrain as ou
from optimtool.base import sp
x1, x2, x3, x4 = sp.symbols("x1 x2 x3 x4") # Declare symbolic variables
f = (x1 - 1)**2 + (x2 - 1)**2 + (x3 - 1)**2 + (x1**2 + x2**2 + x3**2 + x4**2 - 0.25)**2
x_0 = (1, 2, 3, 4) # init data
ou.newton.modified(f, [x1, x2, x3, x4], x_0)
``` 
> x_0 is the initial parameter same as [self.parameters assigned by net.init](https://github.com/google-deepmind/optax/blob/9f2f5caeca3030accf608cce934182798b5da7c6/optax/second_order/hessian_test.py#L51)

so if a complicated function apply on deep learning models to measure accuracy, then a second_order method may be recommended in such issue, the most engineers will adopt some simple functions, like mean square loss according to sequence. If a secord_order method can not be used as a core function to drive the reseach of function with multiple local minima, then it was may not suitable for a simple function with single local minima when a gradient method is enough for any actual deep learning pipeline.

**Comment by mtthss** [comment]
Thanks for sharing!
