### ISSUE TITLE
The citation link is not working

### ISSUE THREAD

**Issue by VhaoYan** [google-deepmind/optax#636]
Hi,

I want to cite the OPTAX in my paper, but the citation link in the README seems not working. "Cite Optax please use the [DeepMind JAX Ecosystem citation](https://github.com/deepmind/jax/blob/main/deepmind2020jax.txt)." Could you please check it? thank you

**Comment by nikosavola** [comment]
Encountered the same

**Comment by mtthss** [comment]
This will be fixed in PR #637
