### ISSUE TITLE
How to optimize multi model’s parameter in one optimizer ?

### ISSUE THREAD

**Issue by GCP20** [google-deepmind/optax#648]
Is there something similar in optax framework ? Or how can I accomplish this use case using optax 

![Screenshot 2023-11-30 at 2 34 21 PM](https://github.com/google-deepmind/optax/assets/87750395/d313e900-c288-4c6b-bc37-60d3a4e83daf)

Link to the page: https://discuss.pytorch.org/t/how-to-optimize-multi-models-parameter-in-one-optimizer/3603

**Comment by holounic** [comment]
Hi @GCP20! Optax expects a PyTree to be passed to the init method of an optimiser. Based on the fact that a tree of PyTrees is also a PyTree, parameters of the models can be composed and fed into an optimiser. You can do something like this:
params = {'w1': model1_params, 'w2': model2_params}
If this doesn't work, I would be happy to help if you could share your particular use case:)

**Comment by Contributorrandom** [comment]
Thank you @holounic . Got it..
