### ISSUE TITLE
Merge the two quickstart notebooks?

### ISSUE THREAD

**Issue by fabianp** [google-deepmind/optax#663]
Currently we have two quickstart notebooks:

* Learn Optax: https://optax.readthedocs.io/en/latest/optax-101.html , featured from the "Getting started" section
* Quickstart with Optax: https://optax.readthedocs.io/en/latest/_collections/examples/quick_start.html , linked only from the Example gallery (but not from the Getting started section).

Since both notebooks are not too long, I think it would be a good idea to merge both, or at least put them together in the same section.

CC @holounic @mtthss @rosshemsley : curious to get your thoughts on this one

**Comment by holounic** [comment]
True! It seems like the notebooks are practically identical. They both mention `GradientTransformation`, `optax.chain`, schedulers, and use generated data to fit a model. Therefore, we can keep one of them.

I suggest that if we choose to keep optax-101, we move it to the examples directory for consistency and add the `open in Colab` button for easy accessibility from GitHub repo.

On the other hand, if we decide to keep the quick start one, we should probably make the model multilayered (and hence the parameters will become dict). This would demonstrate the more common parameters format.

Additionally, we should link the selected example to the "Getting Started" section.
