### ISSUE TITLE
Break the API documentation into subpages

### ISSUE THREAD

**Issue by fabianp** [google-deepmind/optax#676]
Currently https://optax.readthedocs.io/en/latest/api.html is very long and difficult to navigate.

It could probably be improved by splitting it into several subpages and have the different sections appear in the left hand side.

**Comment by mtthss** [comment]
+1

**Comment by Bigpet** [comment]
seems to have been  done by https://github.com/google-deepmind/optax/pull/688

**Comment by fabianp** [comment]
indeed, thanks!
