### ISSUE TITLE
Replace tree_util with tree_utils in docstrings

### ISSUE THREAD

**Issue by fabianp** [google-deepmind/optax#684]
There are a bunch of docstrings in 

https://optax.readthedocs.io/en/latest/api/combining_optimizers.html
https://optax.readthedocs.io/en/latest/api/optimizer_wrappers.html

that use the old tree_util module name

**Comment by amosyou** [comment]
Is this still an open issue? The only function in general utilities is scale_gradient but I don't see any references to tree_util

**Comment by fabianp** [comment]
hey @amosyou , the paths in the issue description were outdated, but the issue is still real 😉 

i've updated the issue description, let me know if it makes more sense now

**Comment by amosyou** [comment]
I see it now, I'll give this a shot tmrw :)

**Comment by amosyou** [comment]
hey @fabianp , to clarify are we aiming to replace calls to `jax.tree_util.tree_map` with `optax.tree_utils._state_utils.tree_map_params`?

**Comment by fabianp** [comment]
Hey, apologies for the ambiguous issue description. The goal is much simpler. The optax.tree_utils module was previously optax.tree_util (without the s). The goal is to rename usages of optax.tree_util to optax.tree_utils

**Comment by amosyou** [comment]
Sorry if I'm missing anything, I'm looking through the repo and I don't see any usages of optax.tree_util, is there a line number you can pinpoint me to?

**Comment by fabianp** [comment]
its mostly in docstrings, such as [image: image.png]

**Comment by fabianp** [comment]
(the bigger issue here is that we're not testing docstrings, which we
should, although that's a bit more ambitious)

**Comment by fabianp** [comment]
its mostly in docstrings such as 
<img width="827" alt="image" src="https://github.com/google-deepmind/optax/assets/277639/b38b2980-cc13-4805-9be6-8418f55d7a7a">

**Comment by fabianp** [comment]
This happens because we're not testing docstrings (which we should)

**Comment by fabianp** [comment]
ooopps, silly me, I was confusing jax.tree_util with optax.tree_utils. This is issue is moot. Sorry about that!
