### ISSUE TITLE
Optax is incompatible with jax==0.4

### ISSUE THREAD

**Issue by wqlevi** [google-deepmind/optax#694]
I was using JAX with Optax on a `CUDA>=12.0` server, where the minimum version of `JAX >=0.4.22`; when I load `optax==0.1.7`,  I got some error out of removed Attribute: 

`AttributeError: module 'jax.numpy' has no attribute 'DeviceArray'`

I did not find any walk-around for this issue, it seems like JAX removed such attribute after some version; Is there any suggestions? BTW, downgrading CUDA seems not plausible, since I do not have the admin rights for this machine.

**Comment by fabianp** [comment]
Hi @wqlevi . Have you tried using the development version of optax? 

pip install git+https://github.com/deepmind/optax.git

**Comment by fabianp** [comment]
closing for now, please reopen if problem persists

**Comment by wqlevi** [comment]
Hi Fabian,

Thanks for your reply, also, sorry for the belated response.

Yes, the dev version ( `v0.2.0` ) works fine and is compatible with the aforementioned dependencies!

Let's keep this issue closed then :)
