### ISSUE TITLE
Statistical Adaptive Stochastic Gradient Methods

### ISSUE THREAD

**Issue by fabianp** [google-deepmind/optax#703]
Implement the SALSA method from 

[Zhang, Pengchuan, et al. "Statistical adaptive stochastic gradient methods." arXiv preprint arXiv:2002.10597 (2020).](https://arxiv.org/pdf/2002.10597.pdf)

**Comment by alirezadamash** [comment]
I am studying the paper, it seems I can connect my brain to the lines of the paper:) let me work on this issue.

**Comment by fabianp** [comment]
All yours @alirezadamash !
