### ISSUE TITLE
Typing annotation incompatible with python 3.8 in v0.1.8

### ISSUE THREAD

**Issue by bastienqb** [google-deepmind/optax#711]
The typing annotation in `contrib/dadapt_adamw.py` --> `betas: tuple[float, float] = (0.9, 0.999)` is incompatible with python 3.8, giving a type error: `TypeError: 'type' object is not subscriptable`. 

However, python 3.8 is accepted if you refer to the `pyproject.toml` file.

Is the `pyproject.toml` file wrong and should only accept python 3.9 and above (as Jax does) or should the typing be adapted to be compatible with python 3.8?

**Comment by chrisflesher** [comment]
Yes, this fails for me also.

**Comment by vroulet** [comment]
Thanks for catching this! #713 will fix that. Also we shall drop support of Python 3.8.
JAX requires also python 3.9 or higher https://github.com/google/jax/blob/main/setup.py.

**Comment by fabianp** [comment]
closing since we now dropped support for 3.8

**Comment by mikesol** [comment]
Apologies if this is the wrong thread, but is there any documentation on using optax on cloud TPUs? TPUs still ship with 3.8 IIRC.

**Comment by fabianp** [comment]
seems to me colab on TPUs uses 3.10

<img width="1467" alt="image" src="https://github.com/google-deepmind/optax/assets/277639/cac6c0b7-593c-41cf-a814-db04ce0b7fe8">

**Comment by fabianp** [comment]
other than that, we support the same versions as JAX, so I would guess that existing guides for running JAX on cloud TPUs should apply to optax? https://cloud.google.com/tpu/docs/run-calculation-jax

**Comment by NoahBPeterson** [comment]
> Apologies if this is the wrong thread, but is there any documentation on using optax on cloud TPUs? TPUs still ship with 3.8 IIRC.

Seconded. I just ran into this issue because the default python version is 3.8 (I followed this tutorial: https://cloud.google.com/tpu/docs/tutorials/LLM/single-device-pax)

**Comment by fabianp** [comment]
thanks for the report, I've filled in a bug for that webpage asking them to upgrade the python version
