### ISSUE TITLE
Remove unnecessary %pip install statements from the notebooks

### ISSUE THREAD

**Issue by fabianp** [google-deepmind/optax#756]
Some notebooks ([example here](https://optax.readthedocs.io/en/latest/_collections/examples/cifar10_resnet.html)) have some unnecessary pip statements (unnecessary in the sense that the example would run in colab just fine without those statements).

Remove those statements for consistency.

**Comment by JayJayleee** [comment]
Can I work on this issue?

**Comment by fabianp** [comment]
Sure! I've assigned it to you :-)
