### ISSUE TITLE
Type annotation for `params` in function `net`

### ISSUE THREAD

**Issue by yixiaoer** [google-deepmind/optax#784]
The type annotation for `params` in the `net` function in [docs/optax-101.ipynb](https://github.com/google-deepmind/optax/blob/54c238c2ca16f1ffedcfe8dc8e5a00a72d97e300/docs/optax-101.ipynb#L309) should be of type `dictionary` or `optax.Params`:

![](https://github.com/google-deepmind/optax/assets/33915732/e4b409e5-aa2a-4706-ae4b-ed1ebdbc9006)

**Comment by fabianp** [comment]
yup, would you be willing to submit a pull request fixing that?
