### ISSUE TITLE
slow examples are not really executed

### ISSUE THREAD

**Issue by fabianp** [google-deepmind/optax#786]
docs/conf.py is supposed to exclude some slow notebooks from running when building the doc:

```
nb_execution_excludepatterns = [
    # slow examples
    '_collections/examples/cifar10_resnet.ipynb'
    '_collections/examples/adversarial_training.ipynb'
]
```

However, https://optax.readthedocs.io/en/latest/_collections/examples/adversarial_training.html is executed as can be seen from the fact that it has a KeyboardInterrupt exception (because its too slow)

**Comment by vroulet** [comment]
Fixed by #788
