### ISSUE TITLE
Broken tarball for release `v0.2.0`

### ISSUE THREAD

**Issue by daskol** [google-deepmind/optax#854]
I am a maintainer of [`optax` package][1] in Archlinux User Repository (AUR). Me and some other users noticed that suddenly hashes of tarball for `v0.2.0` have been changed. It seems that the tag has been moved to another commit. This breaks package installation and system updates for some users due to failed checksum verification. This problem is even more subtle since `pacman` (Archlinux package manager) caches tarballs by name.

[1]: https://aur.archlinux.org/packages/python-optax

**Comment by fabianp** [comment]
oops, yeah, it seems we messed up with the 0.2.0 release. Just made a 0.2.1 release, let me know if that fixed it

**Comment by daskol** [comment]
Yes, it solves the issue. Thank you.

**Comment by fabianp** [comment]
thanks BTW @daskol for maintaining this library package!
