### ISSUE TITLE
Math pseudocode in description of SGD with Nesterov is incorrect

### ISSUE THREAD

**Issue by satyenkale** [google-deepmind/optax#900]
The math pseudocode in the description of SGD with Nesterov is currently given as:
<img width="573" alt="Screenshot 2024-04-03 at 4 12 26 PM" src="https://github.com/google-deepmind/optax/assets/50182298/60977adb-b5d4-4c79-89b8-9ab82191ffe9">

I believe this is incorrect. Apart from the circular definition of  `m_t` in the case when `nesterov = False`, the definition of `m_t` itself should be corrected. The correct set of equations should be:
<img width="636" alt="Screenshot 2024-04-03 at 5 07 24 PM" src="https://github.com/google-deepmind/optax/assets/50182298/ef107b00-7355-4312-bd36-1b59505027b9">

Or alternatively,
<img width="582" alt="Screenshot 2024-04-03 at 5 05 34 PM" src="https://github.com/google-deepmind/optax/assets/50182298/669ae02c-9ece-45e1-84c3-caa98a60ac90">

This can be verified from the equations (3) and (4) in Sutskever et al, [On the importance of initialization and momentum in deep learning](http://proceedings.mlr.press/v28/sutskever13.pdf), 2013, with the change of variables `m_t = -v_t/epsilon` and `alpha_t = epsilon`.

**Comment by satyenkale** [comment]
Apologies, made an indexing error in my correction! The correct equations should be
<img width="623" alt="Screenshot 2024-04-03 at 5 04 54 PM" src="https://github.com/google-deepmind/optax/assets/50182298/3907549e-cacb-4e1b-ab7e-0a24b5ba82f0">

Or alternatively,
<img width="582" alt="Screenshot 2024-04-03 at 5 05 34 PM" src="https://github.com/google-deepmind/optax/assets/50182298/669ae02c-9ece-45e1-84c3-caa98a60ac90">

**Comment by vroulet** [comment]
Ouh right, thank you very much for catching that @satyenkale! Could you make the correction with a quick pr?

**Comment by satyenkale** [comment]
Thanks! I created a PR (https://github.com/google-deepmind/optax/pull/901) but I am not sure if all the checks went through.

**Comment by vroulet** [comment]
Thank you again! It should go through. The bugs in https://github.com/google-deepmind/optax/pull/901 seem to be related to some changes in jax that broke some of our code. We'll investigate that.

**Comment by satyenkale** [comment]
Great, thanks!

**Comment by vroulet** [comment]
Solved in #901. Thanks again!
