### ISSUE TITLE
Failure when running tests (due to new jax release?)

### ISSUE THREAD

**Issue by fabian-sp** [google-deepmind/optax#904]
While developping my branch, since today, the tests are not passing on my machine. I had run the tests two days ago successfully, so I suspect this is due to a change in jax (a new version was released on April 03).

The error message I get when running `test.sh` is 

```
************* Module clipping
optax/_src/clipping.py:153:16: E1102: jnp.greater is not callable (not-callable)
optax/_src/clipping.py:235:17: E1102: jnp.greater is not callable (not-callable)

```

I merged the latest optax `main` into my branch, so I assume that the failure does not come from my branch not being up-to-date.

**Comment by vroulet** [comment]
Fixed by #908. Thanks again!
