### ISSUE TITLE
Implement Schedule-Free Learning

### ISSUE THREAD

**Issue by ameya98** [google-deepmind/optax#910]
From https://github.com/facebookresearch/schedule_free/tree/main by @adefazio and others.

I have a barebones implementation ready at https://gist.github.com/ameya98/7f103501714f4d2fdc0cb793579648d9, and would be happy to merge into Optax.

**Comment by fabianp** [comment]
Thanks @ameya98. There's now an implementation by @nullstring in https://github.com/google-deepmind/optax/pull/911 . Feel free to provide feedback for that pull request!
