### ISSUE TITLE
README: deadlink to "Optax 101" notebook

### ISSUE THREAD

**Issue by jeertmans** [google-deepmind/optax#937]
Hello, it seems like the link here:

https://github.com/google-deepmind/optax/blob/60bb59f97b75eb35f757b0d7e41a8d7fce2f407d/README.md?plain=1#L80

is broken.

I guess this should be updated to point to https://github.com/google-deepmind/optax/blob/main/docs/getting_started.ipynb?

Tip: you can avoid broken links with tools like [`markdown-link-check`](https://github.com/tcort/markdown-link-check).

**Comment by fabianp** [comment]
thanks @jeertmans ! are you willing to provide a pull request to fix this?

and of course, +1 for adding markdown-link-check to the integration tests (but feel free to do so in a separate PR)

**Comment by jeertmans** [comment]
Sure @fabianp, there you go :-)
