### ISSUE TITLE
Add a `nesterov` flag to `radam` optimizer

### ISSUE THREAD

**Issue by carlosgmartin** [google-deepmind/optax#944]
Currently, the following optimizers receive a `nesterov` flag:
- [adam](https://optax.readthedocs.io/en/latest/api/optimizers.html#adam)
- [adamw](https://optax.readthedocs.io/en/latest/api/optimizers.html#adamw)
- [lars](https://optax.readthedocs.io/en/latest/api/optimizers.html#lars)
- [nadam](https://optax.readthedocs.io/en/latest/api/optimizers.html#nadam)
- [nadamw](https://optax.readthedocs.io/en/latest/api/optimizers.html#nadamw)
- [rmsprop](https://optax.readthedocs.io/en/latest/api/optimizers.html#rmsprop)
- [sgd](https://optax.readthedocs.io/en/latest/api/optimizers.html#sgd)

**Feature request:** Add a `nesterov` flag to the following optimizers:
- [x] [radam](https://optax.readthedocs.io/en/latest/api/optimizers.html#radam)

**Comment by vroulet** [comment]
Hello @carlosgmartin,
Would you be willing to do a PR for this? 
For the record, this [paper](https://arxiv.org/pdf/1910.04209.pdf) provides some insights on radam.
