### ISSUE TITLE
Add an assignment problem solver

### ISSUE THREAD

**Issue by carlosgmartin** [google-deepmind/optax#954]
**Feature request:** Add a GPU/TPU-friendly solver for the [assignment problem](https://en.wikipedia.org/wiki/Assignment_problem). For context, see:

1. [scipy.optimize.linear_sum_assignment](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.linear_sum_assignment.html)
2. https://github.com/google/jax/issues/10403
3. https://github.com/google/jax/pull/16974

The last page contains the following comment:

> There is a TPU-friendly implementation of the [Hungarian algorithm](https://en.wikipedia.org/wiki/Hungarian_algorithm) here: https://github.com/google-research/scenic/blob/main/scenic/model_lib/matchers/hungarian_cover.py

Potentially relevant literature:
- [A distributed auction algorithm for the assignment problem](https://ieeexplore-ieee-org.cmu.idm.oclc.org/document/4739098) (2008)
- [Bipartite Graph Matching Computation on GPU](https://link-springer-com.cmu.idm.oclc.org/chapter/10.1007/978-3-642-03641-5_4) (2009)
- [An anytime assignment algorithm: From local task swapping to global optimality](https://link.springer.com/article/10.1007/s10514-013-9351-2) (2013)
- [On implementing 2D rectangular assignment algorithms](https://ieeexplore.ieee.org/document/7738348) (2016)
- [GPU-accelerated Hungarian algorithms for the Linear Assignment Problem](https://www.sciencedirect.com/science/article/abs/pii/S016781911630045X) (2016)
- [Fast block distributed CUDA implementation of the Hungarian algorithm](https://www.sciencedirect.com/science/article/pii/S0743731519302254) (2019)
- [Development of an Accelerating Hungarian Method for Assignment Problems](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3724157) (2021)
- [Algorithm 1015: A Fast Scalable Solver for the Dense Linear (Sum) Assignment Problem](https://dl.acm.org/doi/abs/10.1145/3442348) (2021)
- [New auction algorithms for the assignment problem and extensions](https://www.sciencedirect.com/science/article/pii/S2666720724000134) (2024)

**Comment by carlosgmartin** [comment]
@vroulet What would be the best place to add a solver function? `optax.contrib.linear_assignment_problem`? I can create a draft PR with my current implementation.

**Comment by vroulet** [comment]
Hello @carlosgmartin, 
That's a good question. The contrib folder is more for algorithms that did not pass the test of time (fancy new optimizers for deep learning typically). A linear assignment problem has passed the test of time so I think it should not be in the contrib folder. I think the best would be to follow the structure in scipy, i.e. simply making a new folder called assignment (maybe one day someone will also want to add [quadratic_assignment](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.quadratic_assignment.html#scipy.optimize.quadratic_assignment)).
The most important part here would be to have
1. a clear documentation with doctests,
2. a notebook example to understand how to use it and in which context.
Given your past record of contributions, I think you'll be able to produce such a clean contribution.
Then the main issue as pointed out by Jake in https://github.com/google/jax/pull/16974 is the burden of maintenance. Would you commit to help maintaining that function? (open-source means potentially forever maintenance just for you to be aware)

**Comment by carlosgmartin** [comment]
The linear assignment problem is an important and standard problem in optimization, as you've noted, so I think it's worth adding to optax. To that end, I've started a PR at #1083 and welcome any feedback.

**Comment by carlosgmartin** [comment]
Closed by #1083.
