### ISSUE TITLE
Intended usage of the Sophia optimiser

### ISSUE THREAD

**Issue by vvvm23** [google-deepmind/optax#968]
Hi all,

I noticed in [this commit](https://github.com/google-deepmind/optax/commit/7d43c5c0cc1ab343229c3c394b3179a1404e97e8) that the Sophia optimiser (see [paper](https://arxiv.org/abs/2305.14342)) has been integrated into `optax`.

However, I noticed the estimate of the diagonal hessian is far simpler than either variant proposed in the paper. 
![image](https://github.com/google-deepmind/optax/assets/44398246/2a9fdd82-5d3d-4f10-a5c1-3e52a3cc0c47)

The first uses a Hessian-vector product and the second uses label resampling. However, in the merged version of the code, [we only seem to use the square of the current gradient](https://github.com/google-deepmind/optax/blob/7d43c5c0cc1ab343229c3c394b3179a1404e97e8/optax/contrib/_sophia.py#L94-L103). Furthermore, this comment:
```
update_hessian_every: How often to update the second order terms. As these
      are very cheap to compute, in fact (just squaring gradients), we can leave
      these at 1 by default. Must be >= 1.
```
seems to further contradict the paper, which says the update is quite expensive to compute and is limited to (usually) every ten steps. This is pretty confusing as the api of `optax` makes it seem that all optimisers can be used as drop-in replacements for one another, but here it seems additional work is required to get the behaviour we want.

How should I use the optax version of the optimiser in order to replicate the behaviour in the paper? Can you share example code for doing this?

**Comment by vroulet** [comment]
Thanks for catching this. You are absolutely right.
The implementation of recent optimizers in the contrib folder are the responsibility of the authors adding them.
@rumschuettel can you fix your implementation of the sophia optimizer?

**Comment by jbausch-gdm** [comment]
Good catch indeed! The current version implements the special case of the GNB estimator for a squared loss only (as mentioned in the paper on p. 9) for which we can use the squared gradients to estimate the diagonal of the Hessian. I'll take a look at the other estimators as well.

**Comment by evanatyourservice** [comment]
Yeah I was kind of surprised that pr was merged as well as the squared gradient isn't really up to par with the main magic of sophia. I see the pr to remove sophia, either way, I'll add a pr for my sophia-h implementation in a _sophia_h contrib file. It is very close to levanter's but has some other features and is a tad cleaned up. It does require the loss fn to be passed in, but optax has `GradientTransformationExtraArgs` which allows for that nicely. I could add a well-described error in case a loss fn isn't passed in help people use it more easily.

**Comment by fabianp** [comment]
hey there. Indeed, we plan to remove the current implementation of sophia after this bug report. We would of course be happy to accept contributions of implementations of this solver that don't share the flaws of the current (soon to be removed) implementation.

**Comment by evanatyourservice** [comment]
Ok, I need to make it play nicely with injected hyperparams and then I'll submit a pr

**Comment by fabianp** [comment]
closing this in favor of #979
