### ISSUE TITLE
Support for CSR format sparse matrix in optimizer?

### ISSUE THREAD

**Issue by MoFHeka** [google-deepmind/optax#994]
matrix format:https://jax.readthedocs.io/en/latest/_autosummary/jax.experimental.sparse.BCSR.html#jax.experimental.sparse.BCSR

some feature in deepspeed: https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/ops/csrc/adam/fused_adam_frontend.cpp

**Comment by fabianp** [comment]
I believe that if the matrix format is a pytree (which I think it is), then things should work out of the box?

It would be great if you can check whether things do work out of the box or not.

It would be even more awesome if you can contribute an [example](https://optax.readthedocs.io/en/latest/gallery.html) on using these sparse matrix formats 😉
