### ISSUE TITLE
Stochasticsm in Adam

### ISSUE THREAD

**Issue by Cattaneo123** [google-deepmind/optax#996]
Please forgive me if this is the wrong place for this question. Adam is described in the documentation as SGD, but I was wondering where the randomness actually comes from. I'm currently using a custom gradient and the optimizer does succeed in finding a minimum, but I'm curious as to what it is randomly selecting? Does it select random rows or columns? Does it inject noise? If so where? Does it select a random set of previous steps? I would greatly appreciate some help with this. If this is the wrong place to ask though please let me know so I can go to the correct forum.

**Comment by fabianp** [comment]
the randomness comes from the stochastic gradient. If the gradient is not stochastic but deterministic then the method is deterministic
